//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;


[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("Model1", "FK__acompany___re_id__2C3393D0", "Persons", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.Persons), "acompany_retinue", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MeetingModel.acompany_retinue), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__acompany_retinue__2B3F6F97", "P_attend_m", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.P_attend_m), "acompany_retinue", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MeetingModel.acompany_retinue), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__Admins__dept_id__1CF15040", "Departments", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MeetingModel.Departments), "Admins", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MeetingModel.Admins), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__Admins__id__1BFD2C07", "Users", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.Users), "Admins", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MeetingModel.Admins), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__Meetings__h_name__24927208", "Hotels", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MeetingModel.Hotels), "Meetings", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MeetingModel.Meetings), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__P_attend_m__m_id__286302EC", "Meetings", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.Meetings), "P_attend_m", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MeetingModel.P_attend_m), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__Ordusers__id__1FCDBCEB", "Users", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.Users), "Ordusers", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MeetingModel.Ordusers), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__P_attend___users__276EDEB3", "Users", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.Users), "P_attend_m", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MeetingModel.P_attend_m), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__Users__id__145C0A3F", "Persons", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.Persons), "Users", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MeetingModel.Users), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK__Supadmin__id__173876EA", "Users", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MeetingModel.Users), "Supadmin", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MeetingModel.Supadmin), true)]

#endregion

namespace MeetingModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Model1Container”部分中的连接字符串初始化新 Model1Container 对象。
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Model1Container 对象。
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Model1Container 对象。
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<acompany_retinue> acompany_retinue
        {
            get
            {
                if ((_acompany_retinue == null))
                {
                    _acompany_retinue = base.CreateObjectSet<acompany_retinue>("acompany_retinue");
                }
                return _acompany_retinue;
            }
        }
        private ObjectSet<acompany_retinue> _acompany_retinue;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Admins> Admins
        {
            get
            {
                if ((_Admins == null))
                {
                    _Admins = base.CreateObjectSet<Admins>("Admins");
                }
                return _Admins;
            }
        }
        private ObjectSet<Admins> _Admins;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Departments> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Departments>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Departments> _Departments;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Hotels> Hotels
        {
            get
            {
                if ((_Hotels == null))
                {
                    _Hotels = base.CreateObjectSet<Hotels>("Hotels");
                }
                return _Hotels;
            }
        }
        private ObjectSet<Hotels> _Hotels;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Meetings> Meetings
        {
            get
            {
                if ((_Meetings == null))
                {
                    _Meetings = base.CreateObjectSet<Meetings>("Meetings");
                }
                return _Meetings;
            }
        }
        private ObjectSet<Meetings> _Meetings;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Ordusers> Ordusers
        {
            get
            {
                if ((_Ordusers == null))
                {
                    _Ordusers = base.CreateObjectSet<Ordusers>("Ordusers");
                }
                return _Ordusers;
            }
        }
        private ObjectSet<Ordusers> _Ordusers;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<P_attend_m> P_attend_m
        {
            get
            {
                if ((_P_attend_m == null))
                {
                    _P_attend_m = base.CreateObjectSet<P_attend_m>("P_attend_m");
                }
                return _P_attend_m;
            }
        }
        private ObjectSet<P_attend_m> _P_attend_m;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Persons> Persons
        {
            get
            {
                if ((_Persons == null))
                {
                    _Persons = base.CreateObjectSet<Persons>("Persons");
                }
                return _Persons;
            }
        }
        private ObjectSet<Persons> _Persons;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Supadmin> Supadmin
        {
            get
            {
                if ((_Supadmin == null))
                {
                    _Supadmin = base.CreateObjectSet<Supadmin>("Supadmin");
                }
                return _Supadmin;
            }
        }
        private ObjectSet<Supadmin> _Supadmin;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 acompany_retinue EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToacompany_retinue(acompany_retinue acompany_retinue)
        {
            base.AddObject("acompany_retinue", acompany_retinue);
        }
    
        /// <summary>
        /// 用于向 Admins EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAdmins(Admins admins)
        {
            base.AddObject("Admins", admins);
        }
    
        /// <summary>
        /// 用于向 Departments EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToDepartments(Departments departments)
        {
            base.AddObject("Departments", departments);
        }
    
        /// <summary>
        /// 用于向 Hotels EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToHotels(Hotels hotels)
        {
            base.AddObject("Hotels", hotels);
        }
    
        /// <summary>
        /// 用于向 Meetings EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMeetings(Meetings meetings)
        {
            base.AddObject("Meetings", meetings);
        }
    
        /// <summary>
        /// 用于向 Ordusers EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOrdusers(Ordusers ordusers)
        {
            base.AddObject("Ordusers", ordusers);
        }
    
        /// <summary>
        /// 用于向 P_attend_m EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToP_attend_m(P_attend_m p_attend_m)
        {
            base.AddObject("P_attend_m", p_attend_m);
        }
    
        /// <summary>
        /// 用于向 Persons EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPersons(Persons persons)
        {
            base.AddObject("Persons", persons);
        }
    
        /// <summary>
        /// 用于向 Supadmin EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSupadmin(Supadmin supadmin)
        {
            base.AddObject("Supadmin", supadmin);
        }
    
        /// <summary>
        /// 用于向 Users EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="acompany_retinue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class acompany_retinue : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 acompany_retinue 对象。
        /// </summary>
        /// <param name="users_id">users_id 属性的初始值。</param>
        /// <param name="m_id">m_id 属性的初始值。</param>
        /// <param name="re_id">re_id 属性的初始值。</param>
        /// <param name="roomnumber">roomnumber 属性的初始值。</param>
        public static acompany_retinue Createacompany_retinue(global::System.String users_id, global::System.String m_id, global::System.String re_id, global::System.String roomnumber)
        {
            acompany_retinue acompany_retinue = new acompany_retinue();
            acompany_retinue.users_id = users_id;
            acompany_retinue.m_id = m_id;
            acompany_retinue.re_id = re_id;
            acompany_retinue.roomnumber = roomnumber;
            return acompany_retinue;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String users_id
        {
            get
            {
                return _users_id;
            }
            set
            {
                if (_users_id != value)
                {
                    Onusers_idChanging(value);
                    ReportPropertyChanging("users_id");
                    _users_id = StructuralObject.SetValidValue(value, false, "users_id");
                    ReportPropertyChanged("users_id");
                    Onusers_idChanged();
                }
            }
        }
        private global::System.String _users_id;
        partial void Onusers_idChanging(global::System.String value);
        partial void Onusers_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_id
        {
            get
            {
                return _m_id;
            }
            set
            {
                if (_m_id != value)
                {
                    Onm_idChanging(value);
                    ReportPropertyChanging("m_id");
                    _m_id = StructuralObject.SetValidValue(value, false, "m_id");
                    ReportPropertyChanged("m_id");
                    Onm_idChanged();
                }
            }
        }
        private global::System.String _m_id;
        partial void Onm_idChanging(global::System.String value);
        partial void Onm_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String re_id
        {
            get
            {
                return _re_id;
            }
            set
            {
                if (_re_id != value)
                {
                    Onre_idChanging(value);
                    ReportPropertyChanging("re_id");
                    _re_id = StructuralObject.SetValidValue(value, false, "re_id");
                    ReportPropertyChanged("re_id");
                    Onre_idChanged();
                }
            }
        }
        private global::System.String _re_id;
        partial void Onre_idChanging(global::System.String value);
        partial void Onre_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String roomnumber
        {
            get
            {
                return _roomnumber;
            }
            set
            {
                OnroomnumberChanging(value);
                ReportPropertyChanging("roomnumber");
                _roomnumber = StructuralObject.SetValidValue(value, false, "roomnumber");
                ReportPropertyChanged("roomnumber");
                OnroomnumberChanged();
            }
        }
        private global::System.String _roomnumber;
        partial void OnroomnumberChanging(global::System.String value);
        partial void OnroomnumberChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__acompany___re_id__2C3393D0", "Persons")]
        public Persons Persons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persons>("Model1.FK__acompany___re_id__2C3393D0", "Persons").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persons>("Model1.FK__acompany___re_id__2C3393D0", "Persons").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persons> PersonsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persons>("Model1.FK__acompany___re_id__2C3393D0", "Persons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persons>("Model1.FK__acompany___re_id__2C3393D0", "Persons", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__acompany_retinue__2B3F6F97", "P_attend_m")]
        public P_attend_m P_attend_m
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<P_attend_m>("Model1.FK__acompany_retinue__2B3F6F97", "P_attend_m").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<P_attend_m>("Model1.FK__acompany_retinue__2B3F6F97", "P_attend_m").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<P_attend_m> P_attend_mReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<P_attend_m>("Model1.FK__acompany_retinue__2B3F6F97", "P_attend_m");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<P_attend_m>("Model1.FK__acompany_retinue__2B3F6F97", "P_attend_m", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Admins")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admins : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Admins 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Admins CreateAdmins(global::System.String id)
        {
            Admins admins = new Admins();
            admins.id = id;
            return admins;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dept_id
        {
            get
            {
                return _dept_id;
            }
            set
            {
                Ondept_idChanging(value);
                ReportPropertyChanging("dept_id");
                _dept_id = StructuralObject.SetValidValue(value, true, "dept_id");
                ReportPropertyChanged("dept_id");
                Ondept_idChanged();
            }
        }
        private global::System.String _dept_id;
        partial void Ondept_idChanging(global::System.String value);
        partial void Ondept_idChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Admins__dept_id__1CF15040", "Departments")]
        public Departments Departments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departments>("Model1.FK__Admins__dept_id__1CF15040", "Departments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departments>("Model1.FK__Admins__dept_id__1CF15040", "Departments").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Departments> DepartmentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departments>("Model1.FK__Admins__dept_id__1CF15040", "Departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Departments>("Model1.FK__Admins__dept_id__1CF15040", "Departments", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Admins__id__1BFD2C07", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Admins__id__1BFD2C07", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Admins__id__1BFD2C07", "Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Admins__id__1BFD2C07", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("Model1.FK__Admins__id__1BFD2C07", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Departments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Departments : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Departments 对象。
        /// </summary>
        /// <param name="dept_id">dept_id 属性的初始值。</param>
        public static Departments CreateDepartments(global::System.String dept_id)
        {
            Departments departments = new Departments();
            departments.dept_id = dept_id;
            return departments;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dept_id
        {
            get
            {
                return _dept_id;
            }
            set
            {
                if (_dept_id != value)
                {
                    Ondept_idChanging(value);
                    ReportPropertyChanging("dept_id");
                    _dept_id = StructuralObject.SetValidValue(value, false, "dept_id");
                    ReportPropertyChanged("dept_id");
                    Ondept_idChanged();
                }
            }
        }
        private global::System.String _dept_id;
        partial void Ondept_idChanging(global::System.String value);
        partial void Ondept_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dept_name
        {
            get
            {
                return _dept_name;
            }
            set
            {
                Ondept_nameChanging(value);
                ReportPropertyChanging("dept_name");
                _dept_name = StructuralObject.SetValidValue(value, true, "dept_name");
                ReportPropertyChanged("dept_name");
                Ondept_nameChanged();
            }
        }
        private global::System.String _dept_name;
        partial void Ondept_nameChanging(global::System.String value);
        partial void Ondept_nameChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Admins__dept_id__1CF15040", "Admins")]
        public EntityCollection<Admins> Admins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Admins>("Model1.FK__Admins__dept_id__1CF15040", "Admins");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Admins>("Model1.FK__Admins__dept_id__1CF15040", "Admins", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Hotels")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hotels : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Hotels 对象。
        /// </summary>
        /// <param name="h_name">h_name 属性的初始值。</param>
        /// <param name="h_address">h_address 属性的初始值。</param>
        public static Hotels CreateHotels(global::System.String h_name, global::System.String h_address)
        {
            Hotels hotels = new Hotels();
            hotels.h_name = h_name;
            hotels.h_address = h_address;
            return hotels;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String h_name
        {
            get
            {
                return _h_name;
            }
            set
            {
                if (_h_name != value)
                {
                    Onh_nameChanging(value);
                    ReportPropertyChanging("h_name");
                    _h_name = StructuralObject.SetValidValue(value, false, "h_name");
                    ReportPropertyChanged("h_name");
                    Onh_nameChanged();
                }
            }
        }
        private global::System.String _h_name;
        partial void Onh_nameChanging(global::System.String value);
        partial void Onh_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String h_address
        {
            get
            {
                return _h_address;
            }
            set
            {
                Onh_addressChanging(value);
                ReportPropertyChanging("h_address");
                _h_address = StructuralObject.SetValidValue(value, false, "h_address");
                ReportPropertyChanged("h_address");
                Onh_addressChanged();
            }
        }
        private global::System.String _h_address;
        partial void Onh_addressChanging(global::System.String value);
        partial void Onh_addressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone_number
        {
            get
            {
                return _phone_number;
            }
            set
            {
                Onphone_numberChanging(value);
                ReportPropertyChanging("phone_number");
                _phone_number = StructuralObject.SetValidValue(value, true, "phone_number");
                ReportPropertyChanged("phone_number");
                Onphone_numberChanged();
            }
        }
        private global::System.String _phone_number;
        partial void Onphone_numberChanging(global::System.String value);
        partial void Onphone_numberChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Meetings__h_name__24927208", "Meetings")]
        public EntityCollection<Meetings> Meetings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Meetings>("Model1.FK__Meetings__h_name__24927208", "Meetings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Meetings>("Model1.FK__Meetings__h_name__24927208", "Meetings", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Meetings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Meetings : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Meetings 对象。
        /// </summary>
        /// <param name="m_id">m_id 属性的初始值。</param>
        /// <param name="m_name">m_name 属性的初始值。</param>
        /// <param name="begin_date">begin_date 属性的初始值。</param>
        /// <param name="m_city">m_city 属性的初始值。</param>
        /// <param name="m_address">m_address 属性的初始值。</param>
        public static Meetings CreateMeetings(global::System.String m_id, global::System.String m_name, global::System.DateTime begin_date, global::System.String m_city, global::System.String m_address)
        {
            Meetings meetings = new Meetings();
            meetings.m_id = m_id;
            meetings.m_name = m_name;
            meetings.begin_date = begin_date;
            meetings.m_city = m_city;
            meetings.m_address = m_address;
            return meetings;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_id
        {
            get
            {
                return _m_id;
            }
            set
            {
                if (_m_id != value)
                {
                    Onm_idChanging(value);
                    ReportPropertyChanging("m_id");
                    _m_id = StructuralObject.SetValidValue(value, false, "m_id");
                    ReportPropertyChanged("m_id");
                    Onm_idChanged();
                }
            }
        }
        private global::System.String _m_id;
        partial void Onm_idChanging(global::System.String value);
        partial void Onm_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_name
        {
            get
            {
                return _m_name;
            }
            set
            {
                Onm_nameChanging(value);
                ReportPropertyChanging("m_name");
                _m_name = StructuralObject.SetValidValue(value, false, "m_name");
                ReportPropertyChanged("m_name");
                Onm_nameChanged();
            }
        }
        private global::System.String _m_name;
        partial void Onm_nameChanging(global::System.String value);
        partial void Onm_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pre_num
        {
            get
            {
                return _pre_num;
            }
            set
            {
                Onpre_numChanging(value);
                ReportPropertyChanging("pre_num");
                _pre_num = StructuralObject.SetValidValue(value, "pre_num");
                ReportPropertyChanged("pre_num");
                Onpre_numChanged();
            }
        }
        private Nullable<global::System.Int32> _pre_num;
        partial void Onpre_numChanging(Nullable<global::System.Int32> value);
        partial void Onpre_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> max_num
        {
            get
            {
                return _max_num;
            }
            set
            {
                Onmax_numChanging(value);
                ReportPropertyChanging("max_num");
                _max_num = StructuralObject.SetValidValue(value, "max_num");
                ReportPropertyChanged("max_num");
                Onmax_numChanged();
            }
        }
        private Nullable<global::System.Int32> _max_num;
        partial void Onmax_numChanging(Nullable<global::System.Int32> value);
        partial void Onmax_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String theme
        {
            get
            {
                return _theme;
            }
            set
            {
                OnthemeChanging(value);
                ReportPropertyChanging("theme");
                _theme = StructuralObject.SetValidValue(value, true, "theme");
                ReportPropertyChanged("theme");
                OnthemeChanged();
            }
        }
        private global::System.String _theme;
        partial void OnthemeChanging(global::System.String value);
        partial void OnthemeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime begin_date
        {
            get
            {
                return _begin_date;
            }
            set
            {
                Onbegin_dateChanging(value);
                ReportPropertyChanging("begin_date");
                _begin_date = StructuralObject.SetValidValue(value, "begin_date");
                ReportPropertyChanged("begin_date");
                Onbegin_dateChanged();
            }
        }
        private global::System.DateTime _begin_date;
        partial void Onbegin_dateChanging(global::System.DateTime value);
        partial void Onbegin_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> end_date
        {
            get
            {
                return _end_date;
            }
            set
            {
                Onend_dateChanging(value);
                ReportPropertyChanging("end_date");
                _end_date = StructuralObject.SetValidValue(value, "end_date");
                ReportPropertyChanged("end_date");
                Onend_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _end_date;
        partial void Onend_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onend_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_city
        {
            get
            {
                return _m_city;
            }
            set
            {
                Onm_cityChanging(value);
                ReportPropertyChanging("m_city");
                _m_city = StructuralObject.SetValidValue(value, false, "m_city");
                ReportPropertyChanged("m_city");
                Onm_cityChanged();
            }
        }
        private global::System.String _m_city;
        partial void Onm_cityChanging(global::System.String value);
        partial void Onm_cityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_address
        {
            get
            {
                return _m_address;
            }
            set
            {
                Onm_addressChanging(value);
                ReportPropertyChanging("m_address");
                _m_address = StructuralObject.SetValidValue(value, false, "m_address");
                ReportPropertyChanged("m_address");
                Onm_addressChanged();
            }
        }
        private global::System.String _m_address;
        partial void Onm_addressChanging(global::System.String value);
        partial void Onm_addressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String h_name
        {
            get
            {
                return _h_name;
            }
            set
            {
                Onh_nameChanging(value);
                ReportPropertyChanging("h_name");
                _h_name = StructuralObject.SetValidValue(value, true, "h_name");
                ReportPropertyChanged("h_name");
                Onh_nameChanged();
            }
        }
        private global::System.String _h_name;
        partial void Onh_nameChanging(global::System.String value);
        partial void Onh_nameChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Meetings__h_name__24927208", "Hotels")]
        public Hotels Hotels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotels>("Model1.FK__Meetings__h_name__24927208", "Hotels").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotels>("Model1.FK__Meetings__h_name__24927208", "Hotels").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hotels> HotelsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotels>("Model1.FK__Meetings__h_name__24927208", "Hotels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hotels>("Model1.FK__Meetings__h_name__24927208", "Hotels", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__P_attend_m__m_id__286302EC", "P_attend_m")]
        public EntityCollection<P_attend_m> P_attend_m
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<P_attend_m>("Model1.FK__P_attend_m__m_id__286302EC", "P_attend_m");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<P_attend_m>("Model1.FK__P_attend_m__m_id__286302EC", "P_attend_m", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Ordusers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ordusers : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Ordusers 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Ordusers CreateOrdusers(global::System.String id)
        {
            Ordusers ordusers = new Ordusers();
            ordusers.id = id;
            return ordusers;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Ordusers__id__1FCDBCEB", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Ordusers__id__1FCDBCEB", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Ordusers__id__1FCDBCEB", "Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Ordusers__id__1FCDBCEB", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("Model1.FK__Ordusers__id__1FCDBCEB", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="P_attend_m")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class P_attend_m : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 P_attend_m 对象。
        /// </summary>
        /// <param name="users_id">users_id 属性的初始值。</param>
        /// <param name="m_id">m_id 属性的初始值。</param>
        public static P_attend_m CreateP_attend_m(global::System.String users_id, global::System.String m_id)
        {
            P_attend_m p_attend_m = new P_attend_m();
            p_attend_m.users_id = users_id;
            p_attend_m.m_id = m_id;
            return p_attend_m;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String users_id
        {
            get
            {
                return _users_id;
            }
            set
            {
                if (_users_id != value)
                {
                    Onusers_idChanging(value);
                    ReportPropertyChanging("users_id");
                    _users_id = StructuralObject.SetValidValue(value, false, "users_id");
                    ReportPropertyChanged("users_id");
                    Onusers_idChanged();
                }
            }
        }
        private global::System.String _users_id;
        partial void Onusers_idChanging(global::System.String value);
        partial void Onusers_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_id
        {
            get
            {
                return _m_id;
            }
            set
            {
                if (_m_id != value)
                {
                    Onm_idChanging(value);
                    ReportPropertyChanging("m_id");
                    _m_id = StructuralObject.SetValidValue(value, false, "m_id");
                    ReportPropertyChanged("m_id");
                    Onm_idChanged();
                }
            }
        }
        private global::System.String _m_id;
        partial void Onm_idChanging(global::System.String value);
        partial void Onm_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> arrive_date
        {
            get
            {
                return _arrive_date;
            }
            set
            {
                Onarrive_dateChanging(value);
                ReportPropertyChanging("arrive_date");
                _arrive_date = StructuralObject.SetValidValue(value, "arrive_date");
                ReportPropertyChanged("arrive_date");
                Onarrive_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _arrive_date;
        partial void Onarrive_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onarrive_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String arrive_way
        {
            get
            {
                return _arrive_way;
            }
            set
            {
                Onarrive_wayChanging(value);
                ReportPropertyChanging("arrive_way");
                _arrive_way = StructuralObject.SetValidValue(value, true, "arrive_way");
                ReportPropertyChanged("arrive_way");
                Onarrive_wayChanged();
            }
        }
        private global::System.String _arrive_way;
        partial void Onarrive_wayChanging(global::System.String value);
        partial void Onarrive_wayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> leave_date
        {
            get
            {
                return _leave_date;
            }
            set
            {
                Onleave_dateChanging(value);
                ReportPropertyChanging("leave_date");
                _leave_date = StructuralObject.SetValidValue(value, "leave_date");
                ReportPropertyChanged("leave_date");
                Onleave_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _leave_date;
        partial void Onleave_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onleave_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String leave_way
        {
            get
            {
                return _leave_way;
            }
            set
            {
                Onleave_wayChanging(value);
                ReportPropertyChanging("leave_way");
                _leave_way = StructuralObject.SetValidValue(value, true, "leave_way");
                ReportPropertyChanged("leave_way");
                Onleave_wayChanged();
            }
        }
        private global::System.String _leave_way;
        partial void Onleave_wayChanging(global::System.String value);
        partial void Onleave_wayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String room_number
        {
            get
            {
                return _room_number;
            }
            set
            {
                Onroom_numberChanging(value);
                ReportPropertyChanging("room_number");
                _room_number = StructuralObject.SetValidValue(value, true, "room_number");
                ReportPropertyChanged("room_number");
                Onroom_numberChanged();
            }
        }
        private global::System.String _room_number;
        partial void Onroom_numberChanging(global::System.String value);
        partial void Onroom_numberChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__acompany_retinue__2B3F6F97", "acompany_retinue")]
        public EntityCollection<acompany_retinue> acompany_retinue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<acompany_retinue>("Model1.FK__acompany_retinue__2B3F6F97", "acompany_retinue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<acompany_retinue>("Model1.FK__acompany_retinue__2B3F6F97", "acompany_retinue", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__P_attend_m__m_id__286302EC", "Meetings")]
        public Meetings Meetings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meetings>("Model1.FK__P_attend_m__m_id__286302EC", "Meetings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meetings>("Model1.FK__P_attend_m__m_id__286302EC", "Meetings").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Meetings> MeetingsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meetings>("Model1.FK__P_attend_m__m_id__286302EC", "Meetings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Meetings>("Model1.FK__P_attend_m__m_id__286302EC", "Meetings", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__P_attend___users__276EDEB3", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__P_attend___users__276EDEB3", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__P_attend___users__276EDEB3", "Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__P_attend___users__276EDEB3", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("Model1.FK__P_attend___users__276EDEB3", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Persons")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persons : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Persons 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Persons CreatePersons(global::System.String id)
        {
            Persons persons = new Persons();
            persons.id = id;
            return persons;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true, "gender");
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__acompany___re_id__2C3393D0", "acompany_retinue")]
        public EntityCollection<acompany_retinue> acompany_retinue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<acompany_retinue>("Model1.FK__acompany___re_id__2C3393D0", "acompany_retinue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<acompany_retinue>("Model1.FK__acompany___re_id__2C3393D0", "acompany_retinue", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Users__id__145C0A3F", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Users__id__145C0A3F", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Users__id__145C0A3F", "Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Users__id__145C0A3F", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("Model1.FK__Users__id__145C0A3F", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Supadmin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Supadmin : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Supadmin 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Supadmin CreateSupadmin(global::System.String id)
        {
            Supadmin supadmin = new Supadmin();
            supadmin.id = id;
            return supadmin;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Supadmin__id__173876EA", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Supadmin__id__173876EA", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Supadmin__id__173876EA", "Users").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("Model1.FK__Supadmin__id__173876EA", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("Model1.FK__Supadmin__id__173876EA", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Users 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="psw">psw 属性的初始值。</param>
        /// <param name="e_mail">e_mail 属性的初始值。</param>
        public static Users CreateUsers(global::System.String id, global::System.String psw, global::System.String e_mail)
        {
            Users users = new Users();
            users.id = id;
            users.psw = psw;
            users.e_mail = e_mail;
            return users;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String psw
        {
            get
            {
                return _psw;
            }
            set
            {
                OnpswChanging(value);
                ReportPropertyChanging("psw");
                _psw = StructuralObject.SetValidValue(value, false, "psw");
                ReportPropertyChanged("psw");
                OnpswChanged();
            }
        }
        private global::System.String _psw;
        partial void OnpswChanging(global::System.String value);
        partial void OnpswChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String e_mail
        {
            get
            {
                return _e_mail;
            }
            set
            {
                One_mailChanging(value);
                ReportPropertyChanging("e_mail");
                _e_mail = StructuralObject.SetValidValue(value, false, "e_mail");
                ReportPropertyChanged("e_mail");
                One_mailChanged();
            }
        }
        private global::System.String _e_mail;
        partial void One_mailChanging(global::System.String value);
        partial void One_mailChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Admins__id__1BFD2C07", "Admins")]
        public Admins Admins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Admins>("Model1.FK__Admins__id__1BFD2C07", "Admins").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Admins>("Model1.FK__Admins__id__1BFD2C07", "Admins").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Admins> AdminsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Admins>("Model1.FK__Admins__id__1BFD2C07", "Admins");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Admins>("Model1.FK__Admins__id__1BFD2C07", "Admins", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Ordusers__id__1FCDBCEB", "Ordusers")]
        public Ordusers Ordusers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ordusers>("Model1.FK__Ordusers__id__1FCDBCEB", "Ordusers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ordusers>("Model1.FK__Ordusers__id__1FCDBCEB", "Ordusers").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ordusers> OrdusersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ordusers>("Model1.FK__Ordusers__id__1FCDBCEB", "Ordusers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ordusers>("Model1.FK__Ordusers__id__1FCDBCEB", "Ordusers", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__P_attend___users__276EDEB3", "P_attend_m")]
        public EntityCollection<P_attend_m> P_attend_m
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<P_attend_m>("Model1.FK__P_attend___users__276EDEB3", "P_attend_m");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<P_attend_m>("Model1.FK__P_attend___users__276EDEB3", "P_attend_m", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Users__id__145C0A3F", "Persons")]
        public Persons Persons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persons>("Model1.FK__Users__id__145C0A3F", "Persons").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persons>("Model1.FK__Users__id__145C0A3F", "Persons").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persons> PersonsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persons>("Model1.FK__Users__id__145C0A3F", "Persons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persons>("Model1.FK__Users__id__145C0A3F", "Persons", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK__Supadmin__id__173876EA", "Supadmin")]
        public Supadmin Supadmin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Supadmin>("Model1.FK__Supadmin__id__173876EA", "Supadmin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Supadmin>("Model1.FK__Supadmin__id__173876EA", "Supadmin").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Supadmin> SupadminReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Supadmin>("Model1.FK__Supadmin__id__173876EA", "Supadmin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Supadmin>("Model1.FK__Supadmin__id__173876EA", "Supadmin", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
